name: CI

on:
  pull_request:
    branches:
      - "*"

  push:

jobs:

  helm:
    name: Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: [v1.22.2]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Lint
        run: |
          docker run --rm --interactive --network host \
              --name ct-lint \
              --volume $PWD:/workdir \
              --workdir /workdir/charts/shenyu \
              quay.io/helmpack/chart-testing:v3.4.0 sh -c 'helm dependency update \
               && cd ../.. \
               && helm repo add shenyu https://erdengk.github.io/shenyu-helm-chart \
               && ct lint \
                  --charts charts/shenyu '